server:
  port: ${SERVER_PORT:8080}

error:
  include-message: always
  include-binding-errors: always

spring:
  application:
    name: ms-vidasalud-bff

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
          audiences:
            - api://${AZURE_API_CLIENT_ID}
            - ${AZURE_API_CLIENT_ID}

azure:
  tenant-id: ${AZURE_TENANT_ID}
  api-client-id: ${AZURE_API_CLIENT_ID}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    cl.duoc.vidasalud.bff: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG